package com.example.weglow.ui.theme

import androidx.compose.ui.graphics.Color

val Cream = Color(0xFFF6F1E6)
val CreamDim = Color(0xFFECE3CD)
val Ink = Color(0xFF21201B)
val InkSoft = Color(0xFF4C4A41)
val Charcoal = Color(0xFF23261E)
val Sage = Color(0xFF93A484)
val SageDim = Color(0xFF69795C)
val Clay = Color(0xFFBD6D45)
val Gold = Color(0xFFC89A42)
// Existing prototype palette, centralized without changing current visuals.
val PageBackground = Color(0xFFFFFFFF)
val CardWhite = Color(0xFFE7EDE4)
val FieldWhite = Color(0xFFE7EDE4)
val DarkGreen = Color(0xFF1F3A2C)
val ButtonGreen = Color(0xFF2D4739)
val TextBlack = Color(0xFF1A1A1A)
val PrimaryBlack = Color(0xFF1A1A1A)
val SoftGray = Color(0xFF8E8E8E)
val MintChip = Color(0xFFCCEBC8)
val SelectedGreen = Color(0xFFCCEBC8)
val CoralAccent = Color(0xFFE0846B)
val PairingCoral = Color(0xFFE0846B)
val CardGray = Color(0xFFEDEDE9)
val PillGray = Color(0xFFEDEDE9)
val TrackGray = Color(0xFFE4E4E0)
val GoldBrown = Color(0xFF9C7B52)
val CheckboxGreen = Color(0xFFB8D4B0)
val DoneGreen = Color(0xFF9AD8A8)
val LogoutRed = Color(0xFFC0392B)

// Supporting semantic colors used by scan/results and legacy Figma screens.
val WelcomeBackground = Color(0xFFF2F4F1)
val LoadingBackgroundColor = Color(0xFFFFF8F5)
val SurfaceSubtle = Color(0xFFF7F7F5)
val SurfaceCool = Color(0xFFEAEEE7)
val ConcernDark = Color(0xFF2B2B3D)
val ConcernBrown = Color(0xFF7A3B2E)
val ConcernLavender = Color(0xFFB9AEE0)
val ConcernRose = Color(0xFFE0546B)
val ConcernBlue = Color(0xFF7FB3C7)
val ConcernGold = Color(0xFFC9A227)
val ConcernAmber = Color(0xFFE8B95C)
val SuccessGreen = Color(0xFF6FCF97)
val WarningOrange = Color(0xFFD98A3D)
val WarmGold = Color(0xFFE0A030)
